version: "3"
services:
  server:
    image: backend
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mydb.c6ud1essc7jp.eu-north-1.rds.amazonaws.com:3306/db?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=s12345%#
      - MYSQL_DATABASE=db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=s12345%#

networks:
  springmysql-net: